duration_format:
  default: "w [weeks], d [days], h [hours], m [minutes], s [seconds]"
  description: "This setting determnines how the topic timer will display the remaining time. This is the <a href='https://github.com/jsmreese/moment-duration-format#template'>link</a> you should refer for setting your custom format."